import re

Import('EnvHelper')

envHelper = EnvHelper()
e = envHelper.env

envHelper.useLibrary('transupport')
envHelper.useLibrary('mcgeometry')
envHelper.includePath(e['blitz'])

# 'prog' is a list of files that get built with the 'examples' target
prog = []

prog += e.Program(EnvHelper.OutputDirPath + 'meshTiming', 
			 ['meshTiming.cpp','createGeometry.cpp'])
prog += e.Program(EnvHelper.OutputDirPath + 'meshComparison',
			 ['meshComparison.cpp','createGeometry.cpp','extra/mtrand.cc'])
prog += e.Program(EnvHelper.OutputDirPath + 'trickyGeometry',
			 ['trickyGeometry.cpp','createGeometry.cpp',
                 'visualizeSurfaces.cpp', 'extra/mtrand.cc'])

Alias('examples', prog)
