#import os

Import('env')
Import('useLibrary')
e = env.Clone()

useLibrary(e, 'transupport')
useLibrary(e, 'mcgeometry')

Import('outputDirPath')

sourceFiles = Glob('*.cpp')

env.Append(CPPPATH = 'extra/')
e.Program(outputDirPath + 'meshTiming', 'meshTiming.cpp')



