import re

Import('env')
Import('useLibrary')
e = env.Clone()

useLibrary(e, 'transupport')
useLibrary(e, 'mcgeometry')

Import('outputDirPath')

sourceFiles = Glob('*.cpp', strings=True)

env.Append(CPPPATH = 'extra/')
for file in sourceFiles:
    execName = re.sub(r'\.cpp$','',file)
    e.Program(outputDirPath + execName, file)

