import re

Import('env')
Import('useLibrary')
Import('includePath')
e = env.Clone()

useLibrary(e, 'transupport')
useLibrary(e, 'mcgeometry')
includePath(e, env['blitz'])

Import('outputDirPath')

# 'prog' is a list of files that get built with the 'examples' target
prog = []

prog += e.Program(outputDirPath + 'meshTiming', \
			 ['meshTiming.cpp','createGeometry.cpp'])
prog += e.Program(outputDirPath + 'meshComparison', \
			 ['meshComparison.cpp','createGeometry.cpp','extra/mtrand.cc'])
prog += e.Program(outputDirPath + 'trickyGeometry', \
			 ['trickyGeometry.cpp','createGeometry.cpp', 'visualizeSurfaces.cpp',\
	  			'extra/mtrand.cc'])

Alias('examples', prog)
