#import os

Import('env')
Import('includePath')
e = env.Clone()

includePath(e, env['blitz'])
sourceFiles = Glob('*.cpp')

#Compile all the source files together into a library
lib = e.StaticLibrary(target = 'mcgeometry', source = sourceFiles)
Default(lib)

#Install header files and library file, optionally
Import('installHeaders')
Import('installLibrary')
installHeaders(e, Glob('*.hpp'))
installLibrary(e, lib)

#compile unit tests
SConscript('tests/SConscript')
