#import os

Import('EnvHelper')
Import('projectName')

envHelper = EnvHelper(projectName)
e = envHelper.env

#Compile all the source files together into a library
sourceFiles = Glob('*.cpp')
lib = e.StaticLibrary(target = 'transupport', source = sourceFiles)
Default(lib)

#Install header files (if the user specifies it)
envHelper.installHeaders(Glob('*.hpp'))
envHelper.installLibrary(lib)

#compile unit tests
SConscript('tests/SConscript')
