import re

Import('env')
Import('useLibrary')
e = env.Clone()

useLibrary(e, 'transupport')

Import('outputDirPath')
testDirPath     = outputDirPath + 'test/transupport/'

#testSupportPath = testDirPath + 'aux/'

################## SET UP REAL WORK ##################
# Compile test executables
sourceFiles = Glob('*.cpp', strings=True)

for file in sourceFiles:
	execName = re.sub(r'\.cpp$','',file)
	if (execName != "tTemplate"):
		prog = e.Program(testDirPath + execName, file)
		Alias('test',prog)

# Copy auxiliary files
#auxFiles = Glob('*.in', strings=True)
#e.Install(testSupportPath, auxFiles)

# Copy the python script
runTests = e.Install(outputDirPath + 'test/', 'runTests.py')
Alias('test',runTests)
Import('installBinary')
installBinary(e, 'runTests.py')
