import re

Import('env')
Import('useLibrary')
e = env.Clone()

useLibrary(e, 'transupport')
useLibrary(e, 'mcgeometry')

Import('outputDirPath')
testDirPath     = outputDirPath + 'test/mcgeometry/'

#testSupportPath = testDirPath + 'aux/'

################## SET UP REAL WORK ##################
# Compile test executables
sourceFiles = Glob('*.cpp', strings=True)

for file in sourceFiles:
	execName = re.sub(r'\.cpp$','',file)
	if (execName != "tTemplate"):
		e.Program(testDirPath + execName, file)

# Copy auxiliary files
#auxFiles = Glob('*.in', strings=True)
#e.Install(testSupportPath, auxFiles)
