import re

Import('env')
Import('useLibrary')
e = env.Clone()

useLibrary(e, 'transupport')
useLibrary(e, 'mcgeometry')

Import('outputDirPath')

e.Program(outputDirPath + 'meshTiming', \
			 ['meshTiming.cpp','generateMeshGeom.cpp'])
e.Program(outputDirPath + 'meshComparison', \
			 ['meshComparison.cpp','generateMeshGeom.cpp','extra/mtrand.cc'])
