import re

Import('env')
Import('useLibrary')
e = env.Clone()

useLibrary(e, 'transupport')
useLibrary(e, 'mcgeometry')

Import('outputDirPath')

# 'prog' is a list of files that get built with the 'examples' target
prog = []

prog += e.Program(outputDirPath + 'meshTiming', \
			 ['meshTiming.cpp','generateMeshGeom.cpp'])
prog += e.Program(outputDirPath + 'meshComparison', \
			 ['meshComparison.cpp','generateMeshGeom.cpp','extra/mtrand.cc'])

Alias('examples', prog)
