#import os

Import('env')
Import('useLibrary')
e = env.Clone()

useLibrary(e, 'transupport')
useLibrary(e, 'mcgeometry')

Import('outputDirPath')

sourceFiles = Glob('*.cpp')

e.Program(outputDirPath + 'meshExample', 'meshExample.cpp')



